name: CI TEST

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - ansible

jobs:
  plan:
    if: inputs.action == 'plan'
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

  apply:
    if: inputs.action == 'apply'
    runs-on: self-hosted
    #needs: plan
    steps:
      #- name: Checkout Code
      #  uses: actions/checkout@v4

      #- name: Set up Terraform
      #  uses: hashicorp/setup-terraform@v2
      #  with:
      #    terraform_version: 1.11.4
      #    terraform_wrapper: false

      #- name: Terraform Init
      #  run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

  ansible:
    if: inputs.action == 'ansible'
    runs-on: self-hosted
    #needs: apply
    steps:
      - name: display ansible inventory
        run: cat inventory.txt

      - name: run ansible play
        run: ansible -i inventory.txt all -u ec2-user -m ping
